### PR TITLE
Request data (headers, params, query, body) typecasting with enabled validation

### PR DESCRIPTION
**Pull request by swarthy**
If `validate` configured for route, merge Joi validation result with `req`.

### CODE REVIEW

**Comment by jaumard** [comment]
Hi @swarthy ! :) 
Thanks for contributing ! Can you tell me what the purpose of this ? What will be the use case of this ?

**Comment by swarthy** [comment]
Hi! For example, if we have route like this
```javascript
{
    method: ['PUT'],
    path: '/some/path/with/:id/and/:anotherId',
    handler: 'SomeController.makeMagic',
    config: {
      validate: {
        params: {
          id: Joi.number().integer().positive(),
          anotherId: Joi.number().integer().positive()
        },
        body: {
          field1: Joi.string().min(10).required(),
          field2: Joi.string().email().required()
        }
      }
    }
  }
```
we can skip validation in controller
```javascript
// SomeController.js
...

  makeMagic (req, res) {
    // we saved 1 symbol here :)
   // not if (+req.params.id < 0) {
    if (req.params.id < 0) {
       // some logic
    }
    const someValue = req.body.id * req.body.anotherId
    this.app.orm.someModel.create(req.body) // in body only field1 and field2
    // etc
  }
...
```

**Comment by jaumard** [comment]
But it's already working like this (it suppose too ^^) but here you merge joi results with req. What is that for ?

**Comment by swarthy** [comment]
As I know, Joi doen't mutate validating object, so in controller all fields of query or params are strings (not number, for example)

**Comment by jaumard** [comment]
Ho ok ! Nice I understand now you're right :) yeah everything is in string and it cause some trouble https://github.com/trailsjs/trails/issues/189 ^^ 
Thanks for this !

**Comment by jaumard** [comment]
@scott-wyatt feedbacks on this ? Sounds good to merge for me

**Comment by scott-wyatt** [comment]
This is really nice, I've been doing this manually, but it would be cool to be able to just put it in the route config.

**Comment by scott-wyatt** [comment]
This probably needs a negative test as well.

**Comment by swarthy** [comment]
Em, what kind of test? It just merge objects :)

**Comment by scott-wyatt** [comment]
Opps, I actually missed the point of this PR, I thought this was adding in per route validation into the route config.

**Comment by jaumard** [comment]
Ha ha @scott-wyatt this feature is already done few version ago ^^ so ok I'm merging this ! Thanks @swarthy

**Pull request merged**
