### PR TITLE
add letsencrypt capabilities

### PR DESCRIPTION
**Pull request by jaumard**
Need more tests but here it what it will look like.

Let's encrypt only for in production environment so I force it to production environment only, users that was https for development mode will have to create self signed certificate and it will be used for all env except production.

Let me know what you think about it. Also if you can make some test with this branch see if letsencrypt is working. I'll do some on my side but I'm quite new to it

### CODE REVIEW

**Comment by scott-wyatt** [comment]
This looks pretty good! Here are my thoughts. We are ending into a highly opinionated area here.  While `greenlock` is a good thing, I'm not a 100% sure every dev will agree with it.  There are also a bunch of plugins that this accepts, that would be a pain to add support for each.  My preferences would be to be able to load this is externally.  Perhaps we allow trailpack-express to accept a server parameter or loader instead of hard coding it in?

**Comment by jaumard** [comment]
You're right, my idea was to try to keep it really simple for the users, but I guess with a plugin system it could be as simple a this too. Let's agree on some interface for the plugins in order to achieve the same things then. For me the best way is to have under `web.js` a field `externalConfig` like:

```
externalConfig: (trailsApp, expressApp) => {
   ...
}
```   
But the problem of that will be that you need to duplicate the logic under lib.Server.start in case of non production env 
Any other idea ?

**Comment by scott-wyatt** [comment]
Well, we already have config/env, so I'd say that it could be done there?

**Comment by jaumard** [comment]
@scott-wyatt so basically here nothing more than this right ?

**Comment by scott-wyatt** [comment]
Yeah, that's pretty much it :-)

**Comment by jaumard** [comment]
So if it's ok let's merge this and create a trailpack-letsencrypt then :)

**Pull request merged**
